language: node_js
node_js:
- '12'
install:
- npm i -g gulp
- npm i
script: PROD=true gulp build
deploy:
  provider: gcs
  access_key_id: GOOGUJGWM7B6UHD5XVLTQUQQ
  secret_access_key:
    secure: hzqB663l5AUcQmICenoIygJuccgUeL4dw4omzKy5qJALVV8dCXQZ9fsTC3arwaZflWHv+oiEWNi7C3S25aSkxOK7SfRkz3ip4nB16l4aHjflgk6rAI+0ydMPlpH90VSHxCM8ih8RwCWPJ5WYTQ8KQq1N2jpMfHTuOhxTDo08m1gCG2HWIJkXeF31EilnqijIH3nxkwUB8tZku3hmdZGiES5IoI58UBz6Jo14cyhazwn2welOqA2cfvJn78RgIw6/Omdu/tZyp4yGLI6b0T4BpKVqgeDDWK7RQGZvkXAFrrfuq2r4r5cQVrrdB/aW9dic2/Af0ArWj1V5+gy7OFhUtmJwRomdqtuEBMB5CVNgHxvDiTqLl8U5lQLOEyjLUgOB9goTTB7ujGvs4cgNN8SImMV7WHqPkcc0jcP1HbkRP1H7DFXKolwLx8zCXmw2QAFulr08aSMOEMUzuzt6CwAzz7dHNm5goFHzkRe4ea/6OO0rmBZmBRFZCvcrLpBJm+FNXpwkAFiTY7JDvyLNMCUo60S81stMmWvMhqqoYeQ5X0Nipd9qF8xCo2YGDEVKitt5+4fdjrc1I3MuLEw3GpzrywKATt4hwXB5yb0VGu9b6FxCv1829f/7LtIxGmG7at+G8NFAcdNpk6wRzcWsTm8FyA7Lln/elyQH8+sJmHfAt+Q=
  bucket: clive.io
  skip_cleanup: true
  acl: public-read
  local-dir: dist
  detect_encoding: true
  on:
    branch: master
  edge: true
