language: node_js
node_js:
- '7'
install:
- yarn global add gulp-cli
- yarn
cache:
  yarn: true
  directories:
  - node_modules
  - $(npm config get prefix)/bin/gulp-cli
script: gulp build
deploy:
  provider: gcs
  access_key_id: GOOGSHF7MDYSUFI3TFVN
  secret_access_key:
    secure: "ANimqusGYvxNGkFcOO8Rfo5h/vYKYqdY5vAbZouIhB2RSn5s0grGNYur4hvjGRyKym+U1Kdq9faFH7pVtTb82JQwZ5sTZEykPz6qMRl/ntcduNQTooD+Kvc5y5B9ewTifpWTE43GzPHUhxhzoOqLZarW1c5b1JnMAVAL/r8plY2bdj0tsIgMi63KXiYjcidFIHxV1th3W27cVLKag5cAhYzoD91AQo8xPI2mQERRSnFJqUdgEKMyxOSC7A8djcbjlXgMkLxOEf5x5cI5Sw1GZv17oxTMzLqEx5koXe2hmYYu258rv6JAdoJo+ZhrTT7lS70sxMdELxKP89QAJ65MJFYgjC1Knqy0yljTVzy4xE9rycgy/CSSymNQuZuNFMWCcaV83rP5ENOEl4qjEG00ZXJEwgeTddlCKRb2sz3YRoqKvhNPa2qvfLIYo6/ykuZlwyH2FX/47aOaqVCnBt+i1xFTpd9OoEbkHTRhQzUo4QdgmhpKlYBvZWf7kEoT5IZSDNfpXauFqArQfrXQ8H7Qx5uZEHkIESRBUVN5N3BJoJi8PdJz97N7Ozfzvi5QTrcrvAUCITJRR/mNNuHK+xCtf4WxobReyV1bo5uFXefLVmcE1dL+f6mYp+rEeeMl5Fcsgkt9Lcfzn1vzhOHnobcg/dyLpYFNaoEFyybFuZYy+kI="
  bucket: clive.io
  skip_cleanup: true
  acl: public-read
  local-dir: dist
  detect_encoding: true
  on:
    branch: master
